In [1]:
import numpy as np

# Eixo arbritário
Cria e normaliza o vetor referente ao eixo de rotação, calcula os ângulos de referência e cria as matrizes de rotação direta e inversa.

In [2]:
# Pergunta as coordenadas do vetor de rotação
x = float(input("Digite o valor de x para o eixo arbitrário: "))
y = float(input("Digite o valor de y para o eixo arbitrário: "))
z = float(input("Digite o valor de z para o eixo arbitrário: "))

# Cria o vetor de rotação
v = np.array([x, y, z])

# Normaliza o vetor de rotação
v = v / np.linalg.norm(v)

print(v)

Digite o valor de x para o eixo arbitrário: 1
Digite o valor de y para o eixo arbitrário: 1
Digite o valor de z para o eixo arbitrário: 1
[0.57735027 0.57735027 0.57735027]


In [3]:
# Alpha = arcsin(y/raiz de x^2 + y^2)
alpha = np.arcsin(v[1] / np.sqrt(v[0]**2 + v[1]**2))

# Beta = arccos(z)
beta = np.arccos(v[2])

# Print dos ângulos
print("Alpha: ", alpha)
print("Beta: ", beta)

Alpha:  0.7853981633974484
Beta:  0.9553166181245092


In [4]:
# Cria a matriz de rotação Z (alpha)
Rz = np.array([[np.cos(alpha), -np.sin(alpha), 0],
                [np.sin(alpha), np.cos(alpha), 0],
                [0, 0, 1]])

# Cria a matriz de rotação Y (beta)
Ry = np.array([[np.cos(beta), 0, np.sin(beta)],
                [0, 1, 0],
                [-np.sin(beta), 0, np.cos(beta)]])

# Cria a matriz de rotação final
R1_0 = np.dot(Rz, Ry)

# Cria a matriz de rotação final inversa
R0_1 = np.linalg.inv(R1_0)

# Print das matrizes
print("R1_0: ", R1_0)
print("R0_1: ", R0_1)

R1_0:  [[ 0.40824829 -0.70710678  0.57735027]
 [ 0.40824829  0.70710678  0.57735027]
 [-0.81649658  0.          0.57735027]]
R0_1:  [[ 0.40824829  0.40824829 -0.81649658]
 [-0.70710678  0.70710678 -0.        ]
 [ 0.57735027  0.57735027  0.57735027]]


# Define a rotação
Pergunta ao usuário a rotação em volta do eixo arbritário e define a matriz de rotação final

In [5]:
theta = float(input("Digite o valor de theta: "))

# Transforma o ângulo em radianos
theta = np.deg2rad(theta)

# Cria a matriz de rotação Z (theta)
Rz = np.array([[np.cos(theta), -np.sin(theta), 0],
                [np.sin(theta), np.cos(theta), 0],
                [0, 0, 1]])

# Cria a matriz de rotação final
Rk_theta = np.dot(R1_0, np.dot(Rz, R0_1))

# Print da matriz
print("Rk_theta: ", Rk_theta)

Digite o valor de theta: 90
Rk_theta:  [[ 0.33333333 -0.24401694  0.9106836 ]
 [ 0.9106836   0.33333333 -0.24401694]
 [-0.24401694  0.9106836   0.33333333]]


# Vetor rotacionado
Pergunta ao usuário o vetor que deseja rotacionar, aplica a rotação e exibe o valor final

In [6]:
# Pergunta as coordenadas do vetor
v_x = float(input("Digite o valor de x: "))
v_y = float(input("Digite o valor de y: "))
v_z = float(input("Digite o valor de z: "))

# Cria o vetor
v_p = np.array([v_x, v_y, v_z])

# Cria o vetor rotacionado
v_p_rot = np.dot(Rk_theta, v_p)

# Arreta o vetor rotacionado
v_p_rot = np.round(v_p_rot, 3)

# Print do vetor rotacionado
print("v_p_rot: ", v_p_rot)

Digite o valor de x: 3
Digite o valor de y: 7
Digite o valor de z: 2
v_p_rot:  [1.113 4.577 6.309]
